version: '3'
services:
  api:
    image: redriverserver
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db/demo -user=root -password=pass -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
