version: '3'
services:
  client:
    image: redriver-client
    build: ./client
    env_file: .env
    ports:
      - '8080:80'
  api:
    image: redriver-server
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    env_file: .env
    depends_on:
      - db
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db/${DB_NAME} -user=${DB_USER} -password=${DB_PWD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
